# Dictionary to convert filenames / codes to string run names for printing

filenames = {'xizku':'No SO2 China',
                'xizkw':'No SO2 Europe',
                'xkhqa':'No SO2 India',
                'xizkv':'No SO2 US',
                'xizks':'No SO2 East Asia',
                'xizkm':'No SO2 NHML',
                'xizkq':'No BC NHML',
                'xizky':'No BC US',
                'xizkl':'No BC East Asia',
                'xizkx':'No BC Europe',
  		'xlzci':'No Dust Arabia',
                'xkcxb':'5X SO4',
                'xkcxc':'10X BC',
                'xkcxd':'2X CO2',
                'xkcxe':'3X CH4',
                'xkcxf':'10X Europe SO4',
                'xkcxg':'10X Asia SO4',
                'xkcxh':'pre-industrial SO4',
                'xkcxi':'10X Asia BC',
                'xkcxj':'2% Solar Constant increase',
                'xkcxk':'10X CFC-12',
		'xjndc':'No BC India',
		'xjndd':'No BC East Asia',
		'xjnde':'No SO2 NHML',
		'xjndf':'No BC NHML',
		'xjndh':'No SO2 East Asia',
		'xjndm':'No SO2 China',
		'xjndp':'No SO2 US',
		'xjndq':'No SO2 Europe',
		'xjndr':'No SO2 India',
		'xkyvb':'5X SO4',
		'xkyvc':'10X BC',
		'xkyvd':'2X CO2',
		'xkyve':'3X CH4',
		'xkyvf':'10X Europe SO4',
		'xkyvg':'10X Asia SO4',
		'xkyvh':'pre-industrial SO4',
		'xkyvi':'10X Asia BC',
		'xkyvj':'2% Solar Constant increase',
		'xkyvk':'10X CFC-12',
		'xixam':'No BC Global',
		'xixan':'No OC Global',
		'xixao':'No SO2 Global',	
		'xixav':'2xCO2 Global',
		'xixaq':'No NOX Global',
		'xixar':'No CO Global',
		'xixas':'No VOC Global',
		'xixat':'No CH4 Global',
		'xlnpd':'No BC Global',
		'xlnpj':'No OC Global',
		'xlnpe':'No SO2 Global'

}
